# Change these first
owner: vrxyt # Your GitHub organization or username, where this repository lives
repo: status-l3st # The name of this repository

sites:
  - name: L3ST
    url: https://l3st.pl
  - name: Panel L3ST
    url: https://panel.l3st.pl
  - name: S1.L3ST.PL
    check: "tcp-ping"
    url: 188.64.33.30
    port: 8080
  - name: Mail L3ST
    url: https://mail.l3st.pl
  - name: Test powiadomień discord
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.l3st.pl
  # baseUrl: /status-l3st
  logoUrl: https://raw.githubusercontent.com/vrxyt/status-l3st/master/assets/Vector-3.png
  favicon: https://panel.l3st.pl/storage/d3AtSO9x2kJrJZjFsYfTC58csa42WhdskSaDcCoG.ico
  theme: night
  name: Status L3ST
  introTitle: "**Status L3ST**"
  introMessage: Sprawdź status stron i serwerów w czasie rzeczywistym dzięki naszej platformie monitorującej. L3ST zapewnia szybki i łatwy dostęp do informacji o wydajności i dostępności serwisów online.
  navbar:
    - title: Status
      href: /
    - title: Wsparcie
      href: https://discord.gg/kEkWZssHa5

workflowSchedule:
  graphs: "*/60 * * * *"
  responseTime: "*/60 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Aktywne zdarzenia
  allSystemsOperational: Wszystkie systemy są sprawne
  incidentReport: "Zdarzenie #$NUMBER zobacz raport →"
  activeIncidentSummary: Otwarte w dniu $DATE z $POSTS komentarzami
  incidentTitle: Zdarzenie $NUMBER szczegóły
  incidentDetails: Szczegóły zdarzenia
  incidentFixed: Naprawiono
  incidentOngoing: Trwa
  incidentOpenedAt: Początek
  incidentClosedAt: Koniec
  incidentViewOnGitHub: Wyświetl i subskrybuj w serwisie GitHub
  incidentCommentSummary: Opublikowano $DATE przez $AUTHOR
  incidentBack: ← Powrót do wszystkich zdarzeń
  pastIncidents: Poprzednie zdarzenia
  pastIncidentsResolved: Rozwiązano w $MINUTES minut z $POSTS komentarzami
  liveStatus: Status na żywo
  overallUptime: "Ogólny uptime: $UPTIME"
  overallUptimeTitle: Ogólny uptime
  averageResponseTime: "Średni czas odpowiedzi: $TIMEms"
  averageResponseTimeTitle: Średni czas odpowiedzi
  sevelDayResponseTime: Średni czas odpowiedzi z ost. tygodnia
  responseTimeMs: Czas odpowiedzi (ms)
  up: Aktywny
  down: Offline
  degraded: Zniszczony
  ms: ms
  loading: Ładowanie
  navGitHub: GitHub
  footer: Powered by Upptime and L3ST
  rateLimitExceededTitle: Przekroczony limit żądań
  rateLimitExceededIntro: Przekroczyłeś liczbę żądań, które możesz wykonać w ciągu godziny, więc będziesz musiał poczekać, zanim ponownie uzyskasz dostęp do tej witryny. Alternatywnie możesz dodać swój GitHub Personal Access Token, aby nadal korzystać z tej witryny.
  rateLimitExceededWhatDoesErrorMean: Co oznacza ten błąd?
  rateLimitExceededErrorMeaning: Ta witryna korzysta z interfejsu API GitHub, aby uzyskać dostęp do danych w czasie rzeczywistym na temat stanu naszych witryn. Domyślnie GitHub zezwala każdemu adresowi IP na 60 żądań na godzinę.
  rateLimitExceededErrorHowCanFix: Jak mogę go naprawić?
  rateLimitExceededErrorFix: Możesz poczekać kolejną godzinę, a limit Twojego adresu IP zostanie przywrócony. Alternatywnie możesz dodać swój GitHub Personal Access Token, który zapewnia dodatkowe 5000 żądań na godzinę.
  rateLimitExceededGeneratePAT: Dowiedz się, jak wygenerować swój GitHub Personal Access Token
  rateLimitExceededHasSet: Masz ustawiony osobisty token dostępu.
  rateLimitExceededRemoveToken: Usuń token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Skopiuj i wklej swój token
  rateLimitExceededSaveToken: Zapisz token
  errorTitle: Wystąpił błąd
  errorIntro: Wystąpił błąd podczas próby uzyskania najnowszych informacji o stanie.
  errorText: Możesz spróbować ponownie za kilka chwil.
  errorHome: Przejdź do strony głównej
  pastScheduledMaintenance: Poprzednie zaplanowane prace konserwacyjne
  scheduledMaintenance: Zaplanowane prace konserwacyjne
  scheduledMaintenanceSummaryStarted: Rozpoczęto $DATE na okres $DURATION minut
  scheduledMaintenanceSummaryStarts: Rozpoczęcie $DATE na okres $DURATION minut
  startedAt: Rozpoczęto
  startsAt: Rozpoczęcie
  duration: Duration
  durationMin: $DURATION minut
  incidentCompleted: Ukończona
  incidentScheduled: Zaplanowana
  duration24H: 24h
  duration7D: tydzień
  duration30D: miesiąc
  duration1Y: rok
  durationAll: maks.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
